alfworld-vision:
  env_name: alfworld
  env_config:
    prompt_format: free_think
    use_state_reward: false
    render_mode: text
    alf_config_path: "/home/yaning/workspace/vagen_mine/scripts/exps/prompting/alfworld/alf-config.yaml"
    max_actions_per_step: 1
  train_size: 100
  test_size: 2
